name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Pact provider verification
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get providers needing verfication
        id: get-providers
        ## These actions will live in a different repository but are added locally for demonstration
        uses: ./get-pact-providers-needing-validation
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Pull docker images
        run: docker pull govukpay/postgres:11.1
      - name: Checkout ledger master
        uses: actions/checkout@v2
        with:
          repository: alphagov/pay-ledger
          path: ledger
      - name: Cache Ledger Maven packages
        uses: actions/cache@v2
        with:
          path: ledger/.m2
          key: ${{ runner.os }}-ledger-m2-${{ hashFiles('ledger/pom.xml') }}
          restore-keys: ${{ runner.os }}-ledger-m2
      - name: Run pact provider tests
        uses: ./pact-provider-tests
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
          provider: ledger
          providers-needing-validation: ${{ steps.get-providers.outputs.providers-needing-validation }}
      - name: Checkout adminusers master
        uses: actions/checkout@v2
        with:
          repository: alphagov/pay-adminusers
          path: adminusers
      - name: Cache Adminusers Maven packages
        uses: actions/cache@v2
        with:
          path: adminusers/.m2
          key: ${{ runner.os }}-adminusers-m2-${{ hashFiles('adminusers/pom.xml') }}
          restore-keys: ${{ runner.os }}-adminusers-m2
      - name: Run pact provider tests
        uses: ./pact-provider-tests
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
          provider: adminusers
          providers-needing-validation: ${{ steps.get-providers.outputs.providers-needing-validation }}
